//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public int MaKhuyenMai { get; set; }
        public int MaMonAn { get; set; }
        public Nullable<double> TiLeGiamGia { get; set; }
        public Nullable<System.DateTime> NgayBatDay { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
