//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.MonAn = new HashSet<MonAn>();
        }
    
        public int MaKhuyenMai { get; set; }
        [Display(Name = "Tên")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string TenKhuyenMai { get; set; }
        [Display(Name = "Chi tiết")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string ChiTietKhuyenMai { get; set; }
        [Display(Name = "Hình Ảnh")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string HinhAnh { get; set; }
        [Display(Name = "Người đăng")]
        public Nullable<int> NguoiDang { get; set; }
        [Display(Name = "Ngày đăng")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<System.DateTime> NgayDang { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        [Display(Name = "Ngày kết thúc")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        [Display(Name = "Tỉ lệ giảm giá")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<double> TiLeGiamGia { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonAn> MonAn { get; set; }
    }
}
