//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SuKien
    {
        public int MaSuKien { get; set; }
        [Display(Name = "Tên")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string TenSuKien { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        [Display(Name = "Ngày kết thúc")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        [Display(Name = "Ngày đăng")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<System.DateTime> NgayDang { get; set; }
        [Display(Name = "Hình Ảnh")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string HinhAnh { get; set; }
        [Display(Name = "Chi Tiết")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string ChiTiet { get; set; }
        [Display(Name = "Người đăng")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<int> NguoiDang { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
