//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.DatBan = new HashSet<DatBan>();
            this.KhongGianNhaHang = new HashSet<KhongGianNhaHang>();
            this.KhuyenMai = new HashSet<KhuyenMai>();
            this.SuKien = new HashSet<SuKien>();
            this.TuyenDung = new HashSet<TuyenDung>();
            this.ThongTinNhaHang = new HashSet<ThongTinNhaHang>();
        }
        public int MaTaiKhoan { get; set; }
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string Email { get; set; }
        [Display(Name = "Mật Khẩu")]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Mật khẩu dài từ 6 đến 20 ký tự!")]
        public string MatKhau { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Xác Nhận Mật Khẩu")]
        public string XacNhanMatKhau { get; set; }
        [Display(Name = "Nhớ Mật Khẩu")]
        public Nullable<bool> NhoMatKhau { get; set; }
        [Display(Name = "Loại Tài Khoản")]
        public int LoaiTaiKhoan { get; set; }
        [Display(Name = "Tên Người Dùng")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string TenNguoiDung { get; set; }
        [Display(Name = "Hình Đại Diện")]
        public string HinhAnh { get; set; }
        [Display(Name = "Địa Chỉ")]
        public string DiaChi { get; set; }
        [Display(Name = "Số Diện Thoại")]
        [RegularExpression(@"^\(?([0-9]*)$", ErrorMessage = "{0} không hợp lệ!")]
        [StringLength(11, MinimumLength = 10, ErrorMessage = "Số điện thoại không hợp lệ!")]
        public string SoDienThoai { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatBan> DatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhongGianNhaHang> KhongGianNhaHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai> KhuyenMai { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKien> SuKien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuyenDung> TuyenDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinNhaHang> ThongTinNhaHang { get; set; }
    }
}
