//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThongTinNhaHang
    {
        public int MaThongTin { get; set; }
        [Display(Name = "Người đăng")]
        public int NguoiDang { get; set; }
        [Display(Name = "Map google")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string URLMap { get; set; }
        [Display(Name = "Tên nhà hàng")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string TenNhaHang { get; set; }
        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string DiaChi { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string Email { get; set; }
        [Display(Name = "Số điện thoại 1")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string SoDienThoai1 { get; set; }
        [Display(Name = "Số điện thoại 2")]
        public string SoDienThoai2 { get; set; }
        [Display(Name = "Thông tin khác")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string ThongTinKhac { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
