//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TuyenDung
    {
        public int MaTuyenDung { get; set; }
        [Display(Name = "Tên")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string TenTuyenDung { get; set; }
        [Display(Name = "Ngày đăng")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public System.DateTime NgayDang { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        [Display(Name = "Ngày kêt thúc")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        [Display(Name = "Chi tiết")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string ChiTiet { get; set; }
        [Display(Name = "Người đăng")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public int NguoiDang { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
